# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_null', models.CharField(max_length=30, null=True)),
                ('str_null_blank', models.CharField(blank=True, max_length=30, null=True)),
                ('int_null', models.IntegerField(null=True)),
                ('int_null_blank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
