# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmodel',
            name='int_blank',
            field=models.IntegerField(blank=True, default=1000000),
            preserve_default=False,
        ),
    ]
